    FROM python:3.7
  3 LABEL maintainer="yishusahil@gmail.com"
  4 
  5 
  6 RUN apt-get update
  7 RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  8 RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  9 RUN apt-get -y update && apt-get -y install google-chrome-stable
 10 RUN apt-get install -yqq unzip curl
 11 RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
 12 RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
 13 ENV CHROMEDRIVER_VERSION 87.0.4280.88
 14 ENV ALLURE_VERSION 2.13.3
 15 
 16 RUN python3 -m pip  install selenium
 17 RUN python3 -m pip install nsepy
 18 RUN python3 -m pip install kiteconnect
 19 RUN python3 -m pip install -U python-dotenv
 20 
 21 
 22 
 23 COPY trading /usr/share/app
 24 
 25 WORKDIR /usr/share/app
 26 
                                
